# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from clay_hr_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from clay_hr_python_sdk.api_response import AsyncGeneratorResponse
from clay_hr_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from clay_hr_python_sdk import schemas  # noqa: F401

from clay_hr_python_sdk.model.skills_create_new_skill_response import SkillsCreateNewSkillResponse as SkillsCreateNewSkillResponseSchema
from clay_hr_python_sdk.model.skills_create_new_skill_request import SkillsCreateNewSkillRequest as SkillsCreateNewSkillRequestSchema
from clay_hr_python_sdk.model.skills_create_new_skill_request_skill_type_model import SkillsCreateNewSkillRequestSkillTypeModel as SkillsCreateNewSkillRequestSkillTypeModelSchema
from clay_hr_python_sdk.model.skills_create_new_skill_request_assessment_model import SkillsCreateNewSkillRequestAssessmentModel as SkillsCreateNewSkillRequestAssessmentModelSchema
from clay_hr_python_sdk.model.skills_create_new_skill401_response import SkillsCreateNewSkill401Response as SkillsCreateNewSkill401ResponseSchema
from clay_hr_python_sdk.model.skills_create_new_skill409_response import SkillsCreateNewSkill409Response as SkillsCreateNewSkill409ResponseSchema

from clay_hr_python_sdk.type.skills_create_new_skill_request import SkillsCreateNewSkillRequest
from clay_hr_python_sdk.type.skills_create_new_skill_request_skill_type_model import SkillsCreateNewSkillRequestSkillTypeModel
from clay_hr_python_sdk.type.skills_create_new_skill_request_assessment_model import SkillsCreateNewSkillRequestAssessmentModel
from clay_hr_python_sdk.type.skills_create_new_skill_response import SkillsCreateNewSkillResponse
from clay_hr_python_sdk.type.skills_create_new_skill409_response import SkillsCreateNewSkill409Response
from clay_hr_python_sdk.type.skills_create_new_skill401_response import SkillsCreateNewSkill401Response

from ...api_client import Dictionary
from clay_hr_python_sdk.pydantic.skills_create_new_skill_request_assessment_model import SkillsCreateNewSkillRequestAssessmentModel as SkillsCreateNewSkillRequestAssessmentModelPydantic
from clay_hr_python_sdk.pydantic.skills_create_new_skill_request_skill_type_model import SkillsCreateNewSkillRequestSkillTypeModel as SkillsCreateNewSkillRequestSkillTypeModelPydantic
from clay_hr_python_sdk.pydantic.skills_create_new_skill_request import SkillsCreateNewSkillRequest as SkillsCreateNewSkillRequestPydantic
from clay_hr_python_sdk.pydantic.skills_create_new_skill_response import SkillsCreateNewSkillResponse as SkillsCreateNewSkillResponsePydantic
from clay_hr_python_sdk.pydantic.skills_create_new_skill409_response import SkillsCreateNewSkill409Response as SkillsCreateNewSkill409ResponsePydantic
from clay_hr_python_sdk.pydantic.skills_create_new_skill401_response import SkillsCreateNewSkill401Response as SkillsCreateNewSkill401ResponsePydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = SkillsCreateNewSkillRequestSchema


request_body_skills_create_new_skill_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
_auth = [
    'sec0',
    'sec1',
]
SchemaFor201ResponseBodyApplicationJson = SkillsCreateNewSkillResponseSchema


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: SkillsCreateNewSkillResponse


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: SkillsCreateNewSkillResponse


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = SkillsCreateNewSkill401ResponseSchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: SkillsCreateNewSkill401Response


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: SkillsCreateNewSkill401Response


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
SchemaFor409ResponseBodyApplicationJson = SkillsCreateNewSkill409ResponseSchema


@dataclass
class ApiResponseFor409(api_client.ApiResponse):
    body: SkillsCreateNewSkill409Response


@dataclass
class ApiResponseFor409Async(api_client.AsyncApiResponse):
    body: SkillsCreateNewSkill409Response


_response_for_409 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor409,
    response_cls_async=ApiResponseFor409Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor409ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '201': _response_for_201,
    '401': _response_for_401,
    '409': _response_for_409,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_new_skill_mapped_args(
        self,
        description: str,
        skill_code: str,
        assessment_model: typing.Optional[SkillsCreateNewSkillRequestAssessmentModel] = None,
        skill_type_model: typing.Optional[SkillsCreateNewSkillRequestSkillTypeModel] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if description is not None:
            _body["description"] = description
        if skill_code is not None:
            _body["skillCode"] = skill_code
        if assessment_model is not None:
            _body["assessmentModel"] = assessment_model
        if skill_type_model is not None:
            _body["skillTypeModel"] = skill_type_model
        args.body = _body
        return args

    async def _acreate_new_skill_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Create a new skill
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/skill/add',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_skills_create_new_skill_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_new_skill_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Create a new skill
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/skill/add',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_skills_create_new_skill_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateNewSkillRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_new_skill(
        self,
        description: str,
        skill_code: str,
        assessment_model: typing.Optional[SkillsCreateNewSkillRequestAssessmentModel] = None,
        skill_type_model: typing.Optional[SkillsCreateNewSkillRequestSkillTypeModel] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_new_skill_mapped_args(
            description=description,
            skill_code=skill_code,
            assessment_model=assessment_model,
            skill_type_model=skill_type_model,
        )
        return await self._acreate_new_skill_oapg(
            body=args.body,
            **kwargs,
        )
    
    def create_new_skill(
        self,
        description: str,
        skill_code: str,
        assessment_model: typing.Optional[SkillsCreateNewSkillRequestAssessmentModel] = None,
        skill_type_model: typing.Optional[SkillsCreateNewSkillRequestSkillTypeModel] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_new_skill_mapped_args(
            description=description,
            skill_code=skill_code,
            assessment_model=assessment_model,
            skill_type_model=skill_type_model,
        )
        return self._create_new_skill_oapg(
            body=args.body,
        )

class CreateNewSkill(BaseApi):

    async def acreate_new_skill(
        self,
        description: str,
        skill_code: str,
        assessment_model: typing.Optional[SkillsCreateNewSkillRequestAssessmentModel] = None,
        skill_type_model: typing.Optional[SkillsCreateNewSkillRequestSkillTypeModel] = None,
        validate: bool = False,
        **kwargs,
    ) -> SkillsCreateNewSkillResponsePydantic:
        raw_response = await self.raw.acreate_new_skill(
            description=description,
            skill_code=skill_code,
            assessment_model=assessment_model,
            skill_type_model=skill_type_model,
            **kwargs,
        )
        if validate:
            return SkillsCreateNewSkillResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(SkillsCreateNewSkillResponsePydantic, raw_response.body)
    
    
    def create_new_skill(
        self,
        description: str,
        skill_code: str,
        assessment_model: typing.Optional[SkillsCreateNewSkillRequestAssessmentModel] = None,
        skill_type_model: typing.Optional[SkillsCreateNewSkillRequestSkillTypeModel] = None,
        validate: bool = False,
    ) -> SkillsCreateNewSkillResponsePydantic:
        raw_response = self.raw.create_new_skill(
            description=description,
            skill_code=skill_code,
            assessment_model=assessment_model,
            skill_type_model=skill_type_model,
        )
        if validate:
            return SkillsCreateNewSkillResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(SkillsCreateNewSkillResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        description: str,
        skill_code: str,
        assessment_model: typing.Optional[SkillsCreateNewSkillRequestAssessmentModel] = None,
        skill_type_model: typing.Optional[SkillsCreateNewSkillRequestSkillTypeModel] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_new_skill_mapped_args(
            description=description,
            skill_code=skill_code,
            assessment_model=assessment_model,
            skill_type_model=skill_type_model,
        )
        return await self._acreate_new_skill_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        description: str,
        skill_code: str,
        assessment_model: typing.Optional[SkillsCreateNewSkillRequestAssessmentModel] = None,
        skill_type_model: typing.Optional[SkillsCreateNewSkillRequestSkillTypeModel] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_new_skill_mapped_args(
            description=description,
            skill_code=skill_code,
            assessment_model=assessment_model,
            skill_type_model=skill_type_model,
        )
        return self._create_new_skill_oapg(
            body=args.body,
        )

