# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.timesheets_list_activity_types_by_cid_response_data import TimesheetsListActivityTypesByCidResponseData
from clay_hr_python_sdk import configuration


class TestTimesheetsListActivityTypesByCidResponseData(unittest.TestCase):
    """TimesheetsListActivityTypesByCidResponseData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
