# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.org_units_create_new_org_unit409_response import OrgUnitsCreateNewOrgUnit409Response
from clay_hr_python_sdk import configuration


class TestOrgUnitsCreateNewOrgUnit409Response(unittest.TestCase):
    """OrgUnitsCreateNewOrgUnit409Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
