# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.reports_get_content_for_report404_response import ReportsGetContentForReport404Response
from clay_hr_python_sdk import configuration


class TestReportsGetContentForReport404Response(unittest.TestCase):
    """ReportsGetContentForReport404Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
