# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.people_and_permissions_create_or_update_user_details_request_financial_list_item import PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListItem
from clay_hr_python_sdk import configuration


class TestPeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListItem(unittest.TestCase):
    """PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
