# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.candidates_get_response_data_item import CandidatesGetResponseDataItem
from clay_hr_python_sdk import configuration


class TestCandidatesGetResponseDataItem(unittest.TestCase):
    """CandidatesGetResponseDataItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
