# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.timesheets_get_details_by_timesheet_id404_response import TimesheetsGetDetailsByTimesheetId404Response
from clay_hr_python_sdk import configuration


class TestTimesheetsGetDetailsByTimesheetId404Response(unittest.TestCase):
    """TimesheetsGetDetailsByTimesheetId404Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
