# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.expense_reports_delete_expense_report_response import ExpenseReportsDeleteExpenseReportResponse
from clay_hr_python_sdk import configuration


class TestExpenseReportsDeleteExpenseReportResponse(unittest.TestCase):
    """ExpenseReportsDeleteExpenseReportResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
