# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.leaves_process_leave_by_id409_response import LeavesProcessLeaveById409Response
from clay_hr_python_sdk import configuration


class TestLeavesProcessLeaveById409Response(unittest.TestCase):
    """LeavesProcessLeaveById409Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
