# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.custom_fields_get_by_id_response_data_custom_field_group_model import CustomFieldsGetByIdResponseDataCustomFieldGroupModel
from clay_hr_python_sdk import configuration


class TestCustomFieldsGetByIdResponseDataCustomFieldGroupModel(unittest.TestCase):
    """CustomFieldsGetByIdResponseDataCustomFieldGroupModel unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
