# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.timecards_get_by_user_id401_response import TimecardsGetByUserId401Response
from clay_hr_python_sdk import configuration


class TestTimecardsGetByUserId401Response(unittest.TestCase):
    """TimecardsGetByUserId401Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
