# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.timecards_get_details_by_timecard_id_response import TimecardsGetDetailsByTimecardIdResponse
from clay_hr_python_sdk import configuration


class TestTimecardsGetDetailsByTimecardIdResponse(unittest.TestCase):
    """TimecardsGetDetailsByTimecardIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
