# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.custom_fields_get_value401_response import CustomFieldsGetValue401Response
from clay_hr_python_sdk import configuration


class TestCustomFieldsGetValue401Response(unittest.TestCase):
    """CustomFieldsGetValue401Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
