# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.workflow_parameter_assignment_model import WorkflowParameterAssignmentModel
from clay_hr_python_sdk import configuration


class TestWorkflowParameterAssignmentModel(unittest.TestCase):
    """WorkflowParameterAssignmentModel unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
