# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.document_library_get_attachments409_response import DocumentLibraryGetAttachments409Response
from clay_hr_python_sdk import configuration


class TestDocumentLibraryGetAttachments409Response(unittest.TestCase):
    """DocumentLibraryGetAttachments409Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
