# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.org_relation_save_user_response import OrgRelationSaveUserResponse
from clay_hr_python_sdk import configuration


class TestOrgRelationSaveUserResponse(unittest.TestCase):
    """OrgRelationSaveUserResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
