# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.user_pto_policies_list_pto_policies409_response import UserPtoPoliciesListPtoPolicies409Response
from clay_hr_python_sdk import configuration


class TestUserPtoPoliciesListPtoPolicies409Response(unittest.TestCase):
    """UserPtoPoliciesListPtoPolicies409Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
