# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clay_hr_python_sdk
from clay_hr_python_sdk.model.test_get_test409_response import TestGetTest409Response
from clay_hr_python_sdk import configuration


class TestTestGetTest409Response(unittest.TestCase):
    """TestGetTest409Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
