# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class BankAccountModel(BaseModel):
    account_code: typing.Optional[str] = Field(None, alias='accountCode')

    account_number: typing.Optional[str] = Field(None, alias='accountNumber')

    account_type: typing.Optional[str] = Field(None, alias='accountType')

    bank_account_id: typing.Optional[int] = Field(None, alias='bankAccountId')

    bank_country_id: typing.Optional[int] = Field(None, alias='bankCountryId')

    branch_code: typing.Optional[str] = Field(None, alias='branchCode')

    branch_name: typing.Optional[str] = Field(None, alias='branchName')

    cid: typing.Optional[int] = Field(None, alias='cid')

    country_id: typing.Optional[int] = Field(None, alias='countryId')

    create_user_id: typing.Optional[int] = Field(None, alias='createUserId')

    name: typing.Optional[str] = Field(None, alias='name')

    owner_type: typing.Optional[str] = Field(None, alias='ownerType')

    payment_email: typing.Optional[str] = Field(None, alias='paymentEmail')

    routing_number: typing.Optional[str] = Field(None, alias='routingNumber')

    status: typing.Optional[str] = Field(None, alias='status')

    swift_code: typing.Optional[str] = Field(None, alias='swiftCode')

    user_id: typing.Optional[int] = Field(None, alias='userId')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
