# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from clay_hr_python_sdk.pydantic.timestamp import Timestamp

class CustomFieldGroupModel(BaseModel):
    access: typing.Optional[str] = Field(None, alias='access')

    cfgroupid: typing.Optional[int] = Field(None, alias='cfgroupid')

    cfgroupname: typing.Optional[str] = Field(None, alias='cfgroupname')

    cid: typing.Optional[int] = Field(None, alias='cid')

    createts: typing.Optional[Timestamp] = Field(None, alias='createts')

    has_custom_fields: typing.Optional[bool] = Field(None, alias='hasCustomFields')

    layout: typing.Optional[str] = Field(None, alias='layout')

    object_type: typing.Optional[str] = Field(None, alias='objectType')

    sequence: typing.Optional[int] = Field(None, alias='sequence')

    usergroupid: typing.Optional[int] = Field(None, alias='usergroupid')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
