# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

if TYPE_CHECKING:
    from clay_hr_python_sdk.pydantic.dynamic_form_assignment_model import DynamicFormAssignmentModel
from clay_hr_python_sdk.pydantic.dynamic_form_section_model import DynamicFormSectionModel
from clay_hr_python_sdk.pydantic.timestamp import Timestamp
from clay_hr_python_sdk.pydantic.user_group_model import UserGroupModel
from clay_hr_python_sdk.pydantic.user_view_model import UserViewModel

class DynaFormSectionAssignmentModel(BaseModel):
    assignee_role: typing.Optional[str] = Field(None, alias='assigneeRole')

    cid: typing.Optional[int] = Field(None, alias='cid')

    completed_by: typing.Optional[UserViewModel] = Field(None, alias='completedBy')

    createts: typing.Optional[Timestamp] = Field(None, alias='createts')

    dyna_form_section_assign_id: typing.Optional[int] = Field(None, alias='dynaFormSectionAssignId')

    dynamic_form_assignment_model: typing.Optional['DynamicFormAssignmentModel'] = Field(None, alias='dynamicFormAssignmentModel')

    dynamic_form_section_model: typing.Optional[DynamicFormSectionModel] = Field(None, alias='dynamicFormSectionModel')

    status: typing.Optional[str] = Field(None, alias='status')

    user_group_model: typing.Optional[UserGroupModel] = Field(None, alias='userGroupModel')

    user_view_model: typing.Optional[UserViewModel] = Field(None, alias='userViewModel')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
