# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ExpenseReportsGetCurrenciesResponseDataItem(BaseModel):
    currency_id: typing.Optional[str] = Field(None, alias='currencyId')

    currency_code: typing.Optional[str] = Field(None, alias='currencyCode')

    currency_name: typing.Optional[str] = Field(None, alias='currencyName')

    cid: typing.Optional[str] = Field(None, alias='cid')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
