# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from clay_hr_python_sdk.pydantic.goals_get_goal_response_goal_type_model_assessment_model import GoalsGetGoalResponseGoalTypeModelAssessmentModel

class GoalsGetGoalResponseGoalTypeModel(BaseModel):
    goal_type_id: typing.Optional[str] = Field(None, alias='goalTypeId')

    goal_type_name: typing.Optional[str] = Field(None, alias='goalTypeName')

    goal_type_description: typing.Optional[str] = Field(None, alias='goalTypeDescription')

    assessment_model: typing.Optional[GoalsGetGoalResponseGoalTypeModelAssessmentModel] = Field(None, alias='assessmentModel')

    createts: typing.Optional[int] = Field(None, alias='createts')

    cid: typing.Optional[str] = Field(None, alias='cid')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
