# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from clay_hr_python_sdk.pydantic.goals_get_goal_response_project_model_user_model import GoalsGetGoalResponseProjectModelUserModel

class GoalsGetGoalResponseProjectModel(BaseModel):
    project_id: typing.Optional[str] = Field(None, alias='projectId')

    project_name: typing.Optional[str] = Field(None, alias='projectName')

    project_desc: typing.Optional[str] = Field(None, alias='projectDesc')

    startdate: typing.Optional[str] = Field(None, alias='startdate')

    enddate: typing.Optional[str] = Field(None, alias='enddate')

    contact_person: typing.Optional[str] = Field(None, alias='contactPerson')

    account: typing.Optional[str] = Field(None, alias='account')

    account_model: typing.Optional[str] = Field(None, alias='accountModel')

    user_model_list: typing.Optional[str] = Field(None, alias='userModelList')

    status: typing.Optional[str] = Field(None, alias='status')

    createts: typing.Optional[int] = Field(None, alias='createts')

    short_code: typing.Optional[str] = Field(None, alias='shortCode')

    probability: typing.Optional[str] = Field(None, alias='probability')

    contact_person_name: typing.Optional[str] = Field(None, alias='contactPersonName')

    status_value: typing.Optional[str] = Field(None, alias='statusValue')

    pgroupid: typing.Optional[str] = Field(None, alias='pgroupid')

    puid: typing.Optional[str] = Field(None, alias='puid')

    billing_type: typing.Optional[str] = Field(None, alias='billingType')

    time_sheet_open_to_all: typing.Optional[str] = Field(None, alias='timeSheetOpenToAll')

    user_model: typing.Optional[GoalsGetGoalResponseProjectModelUserModel] = Field(None, alias='userModel')

    project_group_model: typing.Optional[str] = Field(None, alias='projectGroupModel')

    group_name: typing.Optional[str] = Field(None, alias='groupName')

    account_name: typing.Optional[str] = Field(None, alias='accountName')

    pm_mail: typing.Optional[str] = Field(None, alias='pmMail')

    locationid: typing.Optional[str] = Field(None, alias='locationid')

    report_method: typing.Optional[str] = Field(None, alias='reportMethod')

    industry: typing.Optional[str] = Field(None, alias='industry')

    cid: typing.Optional[str] = Field(None, alias='cid')

    is_admin: typing.Optional[str] = Field(None, alias='isAdmin')

    createuserid: typing.Optional[str] = Field(None, alias='createuserid')

    lastupdateuserid: typing.Optional[str] = Field(None, alias='lastupdateuserid')

    admin: typing.Optional[str] = Field(None, alias='admin')

    proj_status: typing.Optional[str] = Field(None, alias='projStatus')

    proj_probability: typing.Optional[str] = Field(None, alias='projProbability')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
