# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class PeopleAndPermissionsGetAllUsersDetailsResponseItemSupervisorModelListItem(BaseModel):
    user_id: typing.Optional[str] = Field(None, alias='userId')

    first_name: typing.Optional[str] = Field(None, alias='firstName')

    # The unique identity of the employee. 
    emp_id: typing.Optional[str] = Field(None, alias='empId')

    last_name: typing.Optional[str] = Field(None, alias='lastName')

    middle_name: typing.Optional[str] = Field(None, alias='middleName')

    email: typing.Optional[str] = Field(None, alias='email')

    display_full_name: typing.Optional[str] = Field(None, alias='displayFullName')

    user_start_date: typing.Optional[str] = Field(None, alias='userStartDate')

    location_id: typing.Optional[str] = Field(None, alias='locationId')

    department_i_d: typing.Optional[str] = Field(None, alias='departmentID')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
