# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from clay_hr_python_sdk.pydantic.user_group_model import UserGroupModel

class PtoPolicyApprovalModel(BaseModel):
    approval_id: typing.Optional[int] = Field(None, alias='approvalId')

    cid: typing.Optional[int] = Field(None, alias='cid')

    create_user_id: typing.Optional[int] = Field(None, alias='createUserId')

    flow_id: typing.Optional[int] = Field(None, alias='flowId')

    level_sequence: typing.Optional[int] = Field(None, alias='levelSequence')

    relation_type: typing.Optional[str] = Field(None, alias='relationType')

    skippable: typing.Optional[int] = Field(None, alias='skippable')

    user_group_model: typing.Optional[UserGroupModel] = Field(None, alias='userGroupModel')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
