# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from clay_hr_python_sdk.pydantic.user_pto_policies_list_pto_policies_response_data import UserPtoPoliciesListPtoPoliciesResponseData

class UserPtoPoliciesListPtoPoliciesResponse(BaseModel):
    data: typing.Optional[UserPtoPoliciesListPtoPoliciesResponseData] = Field(None, alias='data')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
