# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from clay_hr_python_sdk.pydantic.custom_field_value_model import CustomFieldValueModel

class UserProfileModel(BaseModel):
    cid: typing.Optional[int] = Field(None, alias='cid')

    createuserid: typing.Optional[int] = Field(None, alias='createuserid')

    custom_field_value_model_list: typing.Optional[typing.List[CustomFieldValueModel]] = Field(None, alias='customFieldValueModelList')

    manager_profile_id: typing.Optional[int] = Field(None, alias='managerProfileId')

    manager_profile_name: typing.Optional[str] = Field(None, alias='managerProfileName')

    org_id: typing.Optional[int] = Field(None, alias='orgId')

    profile_description: typing.Optional[str] = Field(None, alias='profileDescription')

    profile_id: typing.Optional[int] = Field(None, alias='profileId')

    profile_name: typing.Optional[str] = Field(None, alias='profileName')

    profile_requirements: typing.Optional[str] = Field(None, alias='profileRequirements')

    profile_responsibilities: typing.Optional[str] = Field(None, alias='profileResponsibilities')

    salary_band_currency: typing.Optional[str] = Field(None, alias='salaryBandCurrency')

    salary_band_max: typing.Optional[typing.Union[int, float]] = Field(None, alias='salaryBandMax')

    salary_band_min: typing.Optional[typing.Union[int, float]] = Field(None, alias='salaryBandMin')

    object_name: typing.Optional[str] = Field(None, alias='objectName')

    object_type: typing.Optional[str] = Field(None, alias='objectType')

    objectid: typing.Optional[int] = Field(None, alias='objectid')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
