# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from clay_hr_python_sdk.pydantic.workflow_parameter_model import WorkflowParameterModel

class WorkflowParameterAssignmentModel(BaseModel):
    cid: typing.Optional[int] = Field(None, alias='cid')

    param_name: typing.Optional[str] = Field(None, alias='paramName')

    param_value: typing.Optional[str] = Field(None, alias='paramValue')

    parameter_model: typing.Optional[WorkflowParameterModel] = Field(None, alias='parameterModel')

    user_workflowid: typing.Optional[int] = Field(None, alias='userWorkflowid')

    wa_param_id: typing.Optional[int] = Field(None, alias='waParamId')

    workflow_arg_id: typing.Optional[int] = Field(None, alias='workflowArgId')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
