# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from clay_hr_python_sdk.pydantic.timestamp import Timestamp
from clay_hr_python_sdk.pydantic.user_view_model import UserViewModel

class WorkflowModel(BaseModel):
    description: typing.Optional[str] = Field(None, alias='description')

    cid: typing.Optional[int] = Field(None, alias='cid')

    create_user: typing.Optional[int] = Field(None, alias='createUser')

    create_user_model: typing.Optional[UserViewModel] = Field(None, alias='createUserModel')

    createts: typing.Optional[Timestamp] = Field(None, alias='createts')

    duration: typing.Optional[str] = Field(None, alias='duration')

    object_type: typing.Optional[str] = Field(None, alias='objectType')

    shortcut: typing.Optional[bool] = Field(None, alias='shortcut')

    status: typing.Optional[str] = Field(None, alias='status')

    visibility: typing.Optional[str] = Field(None, alias='visibility')

    workflow_id: typing.Optional[int] = Field(None, alias='workflowId')

    workflow_name: typing.Optional[str] = Field(None, alias='workflowName')

    workflow_type: typing.Optional[str] = Field(None, alias='workflowType')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
