# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from clay_hr_python_sdk.paths.document_library.get import GetAttachmentsRaw
from clay_hr_python_sdk.paths.attachment_download.get import GetDocumentAsByteArrayRaw


class DocumentLibraryApiRaw(
    GetAttachmentsRaw,
    GetDocumentAsByteArrayRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
