# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from clay_hr_python_sdk.paths.goal.post import CreateNewGoalRaw
from clay_hr_python_sdk.paths.deletegoal.delete import DeleteGoalRaw
from clay_hr_python_sdk.paths.goal.get import GetAllGoalsRaw
from clay_hr_python_sdk.paths.getgoal.get import GetGoalRaw
from clay_hr_python_sdk.paths.goal_list.get import GetUserGoalsRaw


class GoalsApiRaw(
    CreateNewGoalRaw,
    DeleteGoalRaw,
    GetAllGoalsRaw,
    GetGoalRaw,
    GetUserGoalsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
