# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from clay_hr_python_sdk.paths.api_jobprofiles.get import GetJobProfiles
from clay_hr_python_sdk.apis.tags.job_profiles_api_raw import JobProfilesApiRaw


class JobProfilesApi(
    GetJobProfiles,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JobProfilesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JobProfilesApiRaw(api_client)
