# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from clay_hr_python_sdk.paths.api_orgrelation_allactive.get import GetAllActiveRaw
from clay_hr_python_sdk.paths.api_orgrelation_org_relations_by_user.get import GetOrgRelationsByUserRaw
from clay_hr_python_sdk.paths.api_orgrelation_save.get import SaveUserRaw


class OrgRelationApiRaw(
    GetAllActiveRaw,
    GetOrgRelationsByUserRaw,
    SaveUserRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
