# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from clay_hr_python_sdk.paths.appraisal_add.post import CreatePerformanceReviewRaw
from clay_hr_python_sdk.paths.appraisal_get_completed_reviews.get import GetCompletedReviewsBasedOnUserIdRaw
from clay_hr_python_sdk.paths.appraisal_user.get import GetPerformanceReviewsRaw
from clay_hr_python_sdk.paths.appraisal_template_list.get import GetTemplatesRaw
from clay_hr_python_sdk.paths.appraisal_bulk_launch.post import LaunchPerformanceReviewsInBulkRaw


class PerformanceReviewApiRaw(
    CreatePerformanceReviewRaw,
    GetCompletedReviewsBasedOnUserIdRaw,
    GetPerformanceReviewsRaw,
    GetTemplatesRaw,
    LaunchPerformanceReviewsInBulkRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
