# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from clay_hr_python_sdk.paths.api_projects_allocation.post import AssignUserAllocation
from clay_hr_python_sdk.paths.api_projects.post import CreateNew
from clay_hr_python_sdk.paths.api_projects_project_id.get import DetailsById
from clay_hr_python_sdk.paths.api_projects_allocation_project_id.get import ListAllocations
from clay_hr_python_sdk.paths.api_projects.get import ListProjects
from clay_hr_python_sdk.apis.tags.project_api_raw import ProjectApiRaw


class ProjectApi(
    AssignUserAllocation,
    CreateNew,
    DetailsById,
    ListAllocations,
    ListProjects,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProjectApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProjectApiRaw(api_client)
