# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from clay_hr_python_sdk.paths.timecard_clock_out.get import ClockOutRaw
from clay_hr_python_sdk.paths.timecard_clockin.post import CreatePastTimecardRaw
from clay_hr_python_sdk.paths.timecard_addtimecard.post import CreateTimecardRaw
from clay_hr_python_sdk.paths.api_user_timecard.get import GetByUserIdRaw
from clay_hr_python_sdk.paths.api_user_timecards.get import GetByUserId0Raw
from clay_hr_python_sdk.paths.api_timecards_details_timecard_id.get import GetDetailsByTimecardIdRaw
from clay_hr_python_sdk.paths.verify_tvc.get import GetTvcForClockinWithQrCodeUsingCidRaw
from clay_hr_python_sdk.paths.timecard.get import GetUserByIdRaw
from clay_hr_python_sdk.paths.register.post import RegisterDeviceForClockInWithAssetModelRaw
from clay_hr_python_sdk.paths.verify_device.get import VerifyDeviceWithDeviceUuidRaw
from clay_hr_python_sdk.paths.verify_user.get import VerifyUserWithUseridRaw


class TimecardsApiRaw(
    ClockOutRaw,
    CreatePastTimecardRaw,
    CreateTimecardRaw,
    GetByUserIdRaw,
    GetByUserId0Raw,
    GetDetailsByTimecardIdRaw,
    GetTvcForClockinWithQrCodeUsingCidRaw,
    GetUserByIdRaw,
    RegisterDeviceForClockInWithAssetModelRaw,
    VerifyDeviceWithDeviceUuidRaw,
    VerifyUserWithUseridRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
