# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from clay_hr_python_sdk.paths.api_v3_task_add.post import CreateNewTaskRaw
from clay_hr_python_sdk.paths.api_v3_task_taskid.get import GetTaskDetailsByTaskIdRaw
from clay_hr_python_sdk.paths.api_v3_tasks.get import GetTasksByUserIdRaw
from clay_hr_python_sdk.paths.api_v3_userworkflows.get import GetUserWorkflowsRaw
from clay_hr_python_sdk.paths.api_workflows.get import GetWorkflowsRaw
from clay_hr_python_sdk.paths.api_v3_userworkflows_userworkflowid.get import ListTasksByUserworkflowIdRaw
from clay_hr_python_sdk.paths.api_v3_task_update_status.post import UpdateStatusTaskRaw


class WorkflowsApiRaw(
    CreateNewTaskRaw,
    GetTaskDetailsByTaskIdRaw,
    GetTasksByUserIdRaw,
    GetUserWorkflowsRaw,
    GetWorkflowsRaw,
    ListTasksByUserworkflowIdRaw,
    UpdateStatusTaskRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
