# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from clay_hr_python_sdk import schemas  # noqa: F401


class CandidatesGetResponseDataItemCandidatePositionsModelListItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            candidatePositionsId = schemas.StrSchema
            candidateId = schemas.StrSchema
            positionid = schemas.StrSchema
            positionName = schemas.StrSchema
            positionDescription = schemas.StrSchema
            responsibilities = schemas.StrSchema
            positionDepartmentId = schemas.StrSchema
            positionLocationId = schemas.StrSchema
            positionProjectId = schemas.StrSchema
            positionProfileId = schemas.StrSchema
            count = schemas.StrSchema
            positioncreatets = schemas.StrSchema
            positionStatusOpenClosed = schemas.StrSchema
            applicationDueDate = schemas.StrSchema
            applicationStatusId = schemas.StrSchema
            applicationStatusValue = schemas.StrSchema
            sequence = schemas.StrSchema
            colorcode = schemas.StrSchema
            systemReco = schemas.StrSchema
            systemRecoHelp = schemas.StrSchema
            candidatePositionCreateTs = schemas.StrSchema
            cid = schemas.StrSchema
            appliedPositions = schemas.StrSchema
            status = schemas.StrSchema
            __annotations__ = {
                "candidatePositionsId": candidatePositionsId,
                "candidateId": candidateId,
                "positionid": positionid,
                "positionName": positionName,
                "positionDescription": positionDescription,
                "responsibilities": responsibilities,
                "positionDepartmentId": positionDepartmentId,
                "positionLocationId": positionLocationId,
                "positionProjectId": positionProjectId,
                "positionProfileId": positionProfileId,
                "count": count,
                "positioncreatets": positioncreatets,
                "positionStatusOpenClosed": positionStatusOpenClosed,
                "applicationDueDate": applicationDueDate,
                "applicationStatusId": applicationStatusId,
                "applicationStatusValue": applicationStatusValue,
                "sequence": sequence,
                "colorcode": colorcode,
                "systemReco": systemReco,
                "systemRecoHelp": systemRecoHelp,
                "candidatePositionCreateTs": candidatePositionCreateTs,
                "cid": cid,
                "appliedPositions": appliedPositions,
                "status": status,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["candidatePositionsId"]) -> MetaOapg.properties.candidatePositionsId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["candidateId"]) -> MetaOapg.properties.candidateId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positionid"]) -> MetaOapg.properties.positionid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positionName"]) -> MetaOapg.properties.positionName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positionDescription"]) -> MetaOapg.properties.positionDescription: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["responsibilities"]) -> MetaOapg.properties.responsibilities: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positionDepartmentId"]) -> MetaOapg.properties.positionDepartmentId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positionLocationId"]) -> MetaOapg.properties.positionLocationId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positionProjectId"]) -> MetaOapg.properties.positionProjectId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positionProfileId"]) -> MetaOapg.properties.positionProfileId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["count"]) -> MetaOapg.properties.count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positioncreatets"]) -> MetaOapg.properties.positioncreatets: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positionStatusOpenClosed"]) -> MetaOapg.properties.positionStatusOpenClosed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["applicationDueDate"]) -> MetaOapg.properties.applicationDueDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["applicationStatusId"]) -> MetaOapg.properties.applicationStatusId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["applicationStatusValue"]) -> MetaOapg.properties.applicationStatusValue: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sequence"]) -> MetaOapg.properties.sequence: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["colorcode"]) -> MetaOapg.properties.colorcode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["systemReco"]) -> MetaOapg.properties.systemReco: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["systemRecoHelp"]) -> MetaOapg.properties.systemRecoHelp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["candidatePositionCreateTs"]) -> MetaOapg.properties.candidatePositionCreateTs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cid"]) -> MetaOapg.properties.cid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["appliedPositions"]) -> MetaOapg.properties.appliedPositions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["candidatePositionsId", "candidateId", "positionid", "positionName", "positionDescription", "responsibilities", "positionDepartmentId", "positionLocationId", "positionProjectId", "positionProfileId", "count", "positioncreatets", "positionStatusOpenClosed", "applicationDueDate", "applicationStatusId", "applicationStatusValue", "sequence", "colorcode", "systemReco", "systemRecoHelp", "candidatePositionCreateTs", "cid", "appliedPositions", "status", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["candidatePositionsId"]) -> typing.Union[MetaOapg.properties.candidatePositionsId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["candidateId"]) -> typing.Union[MetaOapg.properties.candidateId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positionid"]) -> typing.Union[MetaOapg.properties.positionid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positionName"]) -> typing.Union[MetaOapg.properties.positionName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positionDescription"]) -> typing.Union[MetaOapg.properties.positionDescription, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["responsibilities"]) -> typing.Union[MetaOapg.properties.responsibilities, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positionDepartmentId"]) -> typing.Union[MetaOapg.properties.positionDepartmentId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positionLocationId"]) -> typing.Union[MetaOapg.properties.positionLocationId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positionProjectId"]) -> typing.Union[MetaOapg.properties.positionProjectId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positionProfileId"]) -> typing.Union[MetaOapg.properties.positionProfileId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["count"]) -> typing.Union[MetaOapg.properties.count, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positioncreatets"]) -> typing.Union[MetaOapg.properties.positioncreatets, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positionStatusOpenClosed"]) -> typing.Union[MetaOapg.properties.positionStatusOpenClosed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["applicationDueDate"]) -> typing.Union[MetaOapg.properties.applicationDueDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["applicationStatusId"]) -> typing.Union[MetaOapg.properties.applicationStatusId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["applicationStatusValue"]) -> typing.Union[MetaOapg.properties.applicationStatusValue, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sequence"]) -> typing.Union[MetaOapg.properties.sequence, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["colorcode"]) -> typing.Union[MetaOapg.properties.colorcode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["systemReco"]) -> typing.Union[MetaOapg.properties.systemReco, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["systemRecoHelp"]) -> typing.Union[MetaOapg.properties.systemRecoHelp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["candidatePositionCreateTs"]) -> typing.Union[MetaOapg.properties.candidatePositionCreateTs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cid"]) -> typing.Union[MetaOapg.properties.cid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["appliedPositions"]) -> typing.Union[MetaOapg.properties.appliedPositions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["candidatePositionsId", "candidateId", "positionid", "positionName", "positionDescription", "responsibilities", "positionDepartmentId", "positionLocationId", "positionProjectId", "positionProfileId", "count", "positioncreatets", "positionStatusOpenClosed", "applicationDueDate", "applicationStatusId", "applicationStatusValue", "sequence", "colorcode", "systemReco", "systemRecoHelp", "candidatePositionCreateTs", "cid", "appliedPositions", "status", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        candidatePositionsId: typing.Union[MetaOapg.properties.candidatePositionsId, str, schemas.Unset] = schemas.unset,
        candidateId: typing.Union[MetaOapg.properties.candidateId, str, schemas.Unset] = schemas.unset,
        positionid: typing.Union[MetaOapg.properties.positionid, str, schemas.Unset] = schemas.unset,
        positionName: typing.Union[MetaOapg.properties.positionName, str, schemas.Unset] = schemas.unset,
        positionDescription: typing.Union[MetaOapg.properties.positionDescription, str, schemas.Unset] = schemas.unset,
        responsibilities: typing.Union[MetaOapg.properties.responsibilities, str, schemas.Unset] = schemas.unset,
        positionDepartmentId: typing.Union[MetaOapg.properties.positionDepartmentId, str, schemas.Unset] = schemas.unset,
        positionLocationId: typing.Union[MetaOapg.properties.positionLocationId, str, schemas.Unset] = schemas.unset,
        positionProjectId: typing.Union[MetaOapg.properties.positionProjectId, str, schemas.Unset] = schemas.unset,
        positionProfileId: typing.Union[MetaOapg.properties.positionProfileId, str, schemas.Unset] = schemas.unset,
        count: typing.Union[MetaOapg.properties.count, str, schemas.Unset] = schemas.unset,
        positioncreatets: typing.Union[MetaOapg.properties.positioncreatets, str, schemas.Unset] = schemas.unset,
        positionStatusOpenClosed: typing.Union[MetaOapg.properties.positionStatusOpenClosed, str, schemas.Unset] = schemas.unset,
        applicationDueDate: typing.Union[MetaOapg.properties.applicationDueDate, str, schemas.Unset] = schemas.unset,
        applicationStatusId: typing.Union[MetaOapg.properties.applicationStatusId, str, schemas.Unset] = schemas.unset,
        applicationStatusValue: typing.Union[MetaOapg.properties.applicationStatusValue, str, schemas.Unset] = schemas.unset,
        sequence: typing.Union[MetaOapg.properties.sequence, str, schemas.Unset] = schemas.unset,
        colorcode: typing.Union[MetaOapg.properties.colorcode, str, schemas.Unset] = schemas.unset,
        systemReco: typing.Union[MetaOapg.properties.systemReco, str, schemas.Unset] = schemas.unset,
        systemRecoHelp: typing.Union[MetaOapg.properties.systemRecoHelp, str, schemas.Unset] = schemas.unset,
        candidatePositionCreateTs: typing.Union[MetaOapg.properties.candidatePositionCreateTs, str, schemas.Unset] = schemas.unset,
        cid: typing.Union[MetaOapg.properties.cid, str, schemas.Unset] = schemas.unset,
        appliedPositions: typing.Union[MetaOapg.properties.appliedPositions, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CandidatesGetResponseDataItemCandidatePositionsModelListItem':
        return super().__new__(
            cls,
            *args,
            candidatePositionsId=candidatePositionsId,
            candidateId=candidateId,
            positionid=positionid,
            positionName=positionName,
            positionDescription=positionDescription,
            responsibilities=responsibilities,
            positionDepartmentId=positionDepartmentId,
            positionLocationId=positionLocationId,
            positionProjectId=positionProjectId,
            positionProfileId=positionProfileId,
            count=count,
            positioncreatets=positioncreatets,
            positionStatusOpenClosed=positionStatusOpenClosed,
            applicationDueDate=applicationDueDate,
            applicationStatusId=applicationStatusId,
            applicationStatusValue=applicationStatusValue,
            sequence=sequence,
            colorcode=colorcode,
            systemReco=systemReco,
            systemRecoHelp=systemRecoHelp,
            candidatePositionCreateTs=candidatePositionCreateTs,
            cid=cid,
            appliedPositions=appliedPositions,
            status=status,
            _configuration=_configuration,
            **kwargs,
        )
