# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from clay_hr_python_sdk import schemas  # noqa: F401


class DynaFormSectionAssignmentModel(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            assigneeRole = schemas.StrSchema
            cid = schemas.Int32Schema
        
            @staticmethod
            def completedBy() -> typing.Type['UserViewModel']:
                return UserViewModel
        
            @staticmethod
            def createts() -> typing.Type['Timestamp']:
                return Timestamp
            dynaFormSectionAssignId = schemas.Int32Schema
        
            @staticmethod
            def dynamicFormAssignmentModel() -> typing.Type['DynamicFormAssignmentModel']:
                return DynamicFormAssignmentModel
        
            @staticmethod
            def dynamicFormSectionModel() -> typing.Type['DynamicFormSectionModel']:
                return DynamicFormSectionModel
            status = schemas.StrSchema
        
            @staticmethod
            def userGroupModel() -> typing.Type['UserGroupModel']:
                return UserGroupModel
        
            @staticmethod
            def userViewModel() -> typing.Type['UserViewModel']:
                return UserViewModel
            __annotations__ = {
                "assigneeRole": assigneeRole,
                "cid": cid,
                "completedBy": completedBy,
                "createts": createts,
                "dynaFormSectionAssignId": dynaFormSectionAssignId,
                "dynamicFormAssignmentModel": dynamicFormAssignmentModel,
                "dynamicFormSectionModel": dynamicFormSectionModel,
                "status": status,
                "userGroupModel": userGroupModel,
                "userViewModel": userViewModel,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assigneeRole"]) -> MetaOapg.properties.assigneeRole: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cid"]) -> MetaOapg.properties.cid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["completedBy"]) -> 'UserViewModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createts"]) -> 'Timestamp': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dynaFormSectionAssignId"]) -> MetaOapg.properties.dynaFormSectionAssignId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dynamicFormAssignmentModel"]) -> 'DynamicFormAssignmentModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dynamicFormSectionModel"]) -> 'DynamicFormSectionModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userGroupModel"]) -> 'UserGroupModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userViewModel"]) -> 'UserViewModel': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["assigneeRole", "cid", "completedBy", "createts", "dynaFormSectionAssignId", "dynamicFormAssignmentModel", "dynamicFormSectionModel", "status", "userGroupModel", "userViewModel", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assigneeRole"]) -> typing.Union[MetaOapg.properties.assigneeRole, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cid"]) -> typing.Union[MetaOapg.properties.cid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["completedBy"]) -> typing.Union['UserViewModel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createts"]) -> typing.Union['Timestamp', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dynaFormSectionAssignId"]) -> typing.Union[MetaOapg.properties.dynaFormSectionAssignId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dynamicFormAssignmentModel"]) -> typing.Union['DynamicFormAssignmentModel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dynamicFormSectionModel"]) -> typing.Union['DynamicFormSectionModel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userGroupModel"]) -> typing.Union['UserGroupModel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userViewModel"]) -> typing.Union['UserViewModel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["assigneeRole", "cid", "completedBy", "createts", "dynaFormSectionAssignId", "dynamicFormAssignmentModel", "dynamicFormSectionModel", "status", "userGroupModel", "userViewModel", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        assigneeRole: typing.Union[MetaOapg.properties.assigneeRole, str, schemas.Unset] = schemas.unset,
        cid: typing.Union[MetaOapg.properties.cid, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        completedBy: typing.Union['UserViewModel', schemas.Unset] = schemas.unset,
        createts: typing.Union['Timestamp', schemas.Unset] = schemas.unset,
        dynaFormSectionAssignId: typing.Union[MetaOapg.properties.dynaFormSectionAssignId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        dynamicFormAssignmentModel: typing.Union['DynamicFormAssignmentModel', schemas.Unset] = schemas.unset,
        dynamicFormSectionModel: typing.Union['DynamicFormSectionModel', schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        userGroupModel: typing.Union['UserGroupModel', schemas.Unset] = schemas.unset,
        userViewModel: typing.Union['UserViewModel', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DynaFormSectionAssignmentModel':
        return super().__new__(
            cls,
            *args,
            assigneeRole=assigneeRole,
            cid=cid,
            completedBy=completedBy,
            createts=createts,
            dynaFormSectionAssignId=dynaFormSectionAssignId,
            dynamicFormAssignmentModel=dynamicFormAssignmentModel,
            dynamicFormSectionModel=dynamicFormSectionModel,
            status=status,
            userGroupModel=userGroupModel,
            userViewModel=userViewModel,
            _configuration=_configuration,
            **kwargs,
        )

from clay_hr_python_sdk.model.dynamic_form_assignment_model import DynamicFormAssignmentModel
from clay_hr_python_sdk.model.dynamic_form_section_model import DynamicFormSectionModel
from clay_hr_python_sdk.model.timestamp import Timestamp
from clay_hr_python_sdk.model.user_group_model import UserGroupModel
from clay_hr_python_sdk.model.user_view_model import UserViewModel
