# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from clay_hr_python_sdk import schemas  # noqa: F401


class FeedbackListFeedbackResponseFeedbackListItemAssignedUserModelLocationModel(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            locationId = schemas.StrSchema
            locationName = schemas.StrSchema
            cid = schemas.StrSchema
            locationDescription = schemas.StrSchema
            locationType = schemas.StrSchema
            address = schemas.StrSchema
            lattitude = schemas.StrSchema
            longitude = schemas.StrSchema
            locationUID = schemas.StrSchema
            status = schemas.StrSchema
            workingDays = schemas.StrSchema
            locationCode = schemas.StrSchema
            locationLabel = schemas.StrSchema
            parentLocationId = schemas.StrSchema
            createuserid = schemas.StrSchema
        
            @staticmethod
            def addressModelList() -> typing.Type['FeedbackListFeedbackResponseFeedbackListItemAssignedUserModelLocationModelAddressModelList']:
                return FeedbackListFeedbackResponseFeedbackListItemAssignedUserModelLocationModelAddressModelList
            __annotations__ = {
                "locationId": locationId,
                "locationName": locationName,
                "cid": cid,
                "locationDescription": locationDescription,
                "locationType": locationType,
                "address": address,
                "lattitude": lattitude,
                "longitude": longitude,
                "locationUID": locationUID,
                "status": status,
                "workingDays": workingDays,
                "locationCode": locationCode,
                "locationLabel": locationLabel,
                "parentLocationId": parentLocationId,
                "createuserid": createuserid,
                "addressModelList": addressModelList,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locationId"]) -> MetaOapg.properties.locationId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locationName"]) -> MetaOapg.properties.locationName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cid"]) -> MetaOapg.properties.cid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locationDescription"]) -> MetaOapg.properties.locationDescription: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locationType"]) -> MetaOapg.properties.locationType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address"]) -> MetaOapg.properties.address: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lattitude"]) -> MetaOapg.properties.lattitude: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["longitude"]) -> MetaOapg.properties.longitude: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locationUID"]) -> MetaOapg.properties.locationUID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["workingDays"]) -> MetaOapg.properties.workingDays: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locationCode"]) -> MetaOapg.properties.locationCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locationLabel"]) -> MetaOapg.properties.locationLabel: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["parentLocationId"]) -> MetaOapg.properties.parentLocationId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createuserid"]) -> MetaOapg.properties.createuserid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["addressModelList"]) -> 'FeedbackListFeedbackResponseFeedbackListItemAssignedUserModelLocationModelAddressModelList': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["locationId", "locationName", "cid", "locationDescription", "locationType", "address", "lattitude", "longitude", "locationUID", "status", "workingDays", "locationCode", "locationLabel", "parentLocationId", "createuserid", "addressModelList", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locationId"]) -> typing.Union[MetaOapg.properties.locationId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locationName"]) -> typing.Union[MetaOapg.properties.locationName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cid"]) -> typing.Union[MetaOapg.properties.cid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locationDescription"]) -> typing.Union[MetaOapg.properties.locationDescription, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locationType"]) -> typing.Union[MetaOapg.properties.locationType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address"]) -> typing.Union[MetaOapg.properties.address, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lattitude"]) -> typing.Union[MetaOapg.properties.lattitude, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["longitude"]) -> typing.Union[MetaOapg.properties.longitude, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locationUID"]) -> typing.Union[MetaOapg.properties.locationUID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["workingDays"]) -> typing.Union[MetaOapg.properties.workingDays, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locationCode"]) -> typing.Union[MetaOapg.properties.locationCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locationLabel"]) -> typing.Union[MetaOapg.properties.locationLabel, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["parentLocationId"]) -> typing.Union[MetaOapg.properties.parentLocationId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createuserid"]) -> typing.Union[MetaOapg.properties.createuserid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["addressModelList"]) -> typing.Union['FeedbackListFeedbackResponseFeedbackListItemAssignedUserModelLocationModelAddressModelList', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["locationId", "locationName", "cid", "locationDescription", "locationType", "address", "lattitude", "longitude", "locationUID", "status", "workingDays", "locationCode", "locationLabel", "parentLocationId", "createuserid", "addressModelList", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        locationId: typing.Union[MetaOapg.properties.locationId, str, schemas.Unset] = schemas.unset,
        locationName: typing.Union[MetaOapg.properties.locationName, str, schemas.Unset] = schemas.unset,
        cid: typing.Union[MetaOapg.properties.cid, str, schemas.Unset] = schemas.unset,
        locationDescription: typing.Union[MetaOapg.properties.locationDescription, str, schemas.Unset] = schemas.unset,
        locationType: typing.Union[MetaOapg.properties.locationType, str, schemas.Unset] = schemas.unset,
        address: typing.Union[MetaOapg.properties.address, str, schemas.Unset] = schemas.unset,
        lattitude: typing.Union[MetaOapg.properties.lattitude, str, schemas.Unset] = schemas.unset,
        longitude: typing.Union[MetaOapg.properties.longitude, str, schemas.Unset] = schemas.unset,
        locationUID: typing.Union[MetaOapg.properties.locationUID, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        workingDays: typing.Union[MetaOapg.properties.workingDays, str, schemas.Unset] = schemas.unset,
        locationCode: typing.Union[MetaOapg.properties.locationCode, str, schemas.Unset] = schemas.unset,
        locationLabel: typing.Union[MetaOapg.properties.locationLabel, str, schemas.Unset] = schemas.unset,
        parentLocationId: typing.Union[MetaOapg.properties.parentLocationId, str, schemas.Unset] = schemas.unset,
        createuserid: typing.Union[MetaOapg.properties.createuserid, str, schemas.Unset] = schemas.unset,
        addressModelList: typing.Union['FeedbackListFeedbackResponseFeedbackListItemAssignedUserModelLocationModelAddressModelList', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FeedbackListFeedbackResponseFeedbackListItemAssignedUserModelLocationModel':
        return super().__new__(
            cls,
            *args,
            locationId=locationId,
            locationName=locationName,
            cid=cid,
            locationDescription=locationDescription,
            locationType=locationType,
            address=address,
            lattitude=lattitude,
            longitude=longitude,
            locationUID=locationUID,
            status=status,
            workingDays=workingDays,
            locationCode=locationCode,
            locationLabel=locationLabel,
            parentLocationId=parentLocationId,
            createuserid=createuserid,
            addressModelList=addressModelList,
            _configuration=_configuration,
            **kwargs,
        )

from clay_hr_python_sdk.model.feedback_list_feedback_response_feedback_list_item_assigned_user_model_location_model_address_model_list import FeedbackListFeedbackResponseFeedbackListItemAssignedUserModelLocationModelAddressModelList
