# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from clay_hr_python_sdk import schemas  # noqa: F401


class SkillTypeModel(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            cid = schemas.Int32Schema
            createUserId = schemas.Int32Schema
            createts = schemas.DateSchema
            skillTypeDesc = schemas.StrSchema
            skillTypeId = schemas.Int32Schema
            skillTypeName = schemas.StrSchema
            
            
            class skillViewModelList(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SkillViewModel']:
                        return SkillViewModel
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['SkillViewModel'], typing.List['SkillViewModel']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'skillViewModelList':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'SkillViewModel':
                    return super().__getitem__(i)
            __annotations__ = {
                "cid": cid,
                "createUserId": createUserId,
                "createts": createts,
                "skillTypeDesc": skillTypeDesc,
                "skillTypeId": skillTypeId,
                "skillTypeName": skillTypeName,
                "skillViewModelList": skillViewModelList,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cid"]) -> MetaOapg.properties.cid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createUserId"]) -> MetaOapg.properties.createUserId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createts"]) -> MetaOapg.properties.createts: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["skillTypeDesc"]) -> MetaOapg.properties.skillTypeDesc: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["skillTypeId"]) -> MetaOapg.properties.skillTypeId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["skillTypeName"]) -> MetaOapg.properties.skillTypeName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["skillViewModelList"]) -> MetaOapg.properties.skillViewModelList: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cid", "createUserId", "createts", "skillTypeDesc", "skillTypeId", "skillTypeName", "skillViewModelList", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cid"]) -> typing.Union[MetaOapg.properties.cid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createUserId"]) -> typing.Union[MetaOapg.properties.createUserId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createts"]) -> typing.Union[MetaOapg.properties.createts, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["skillTypeDesc"]) -> typing.Union[MetaOapg.properties.skillTypeDesc, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["skillTypeId"]) -> typing.Union[MetaOapg.properties.skillTypeId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["skillTypeName"]) -> typing.Union[MetaOapg.properties.skillTypeName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["skillViewModelList"]) -> typing.Union[MetaOapg.properties.skillViewModelList, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cid", "createUserId", "createts", "skillTypeDesc", "skillTypeId", "skillTypeName", "skillViewModelList", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cid: typing.Union[MetaOapg.properties.cid, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        createUserId: typing.Union[MetaOapg.properties.createUserId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        createts: typing.Union[MetaOapg.properties.createts, str, date, schemas.Unset] = schemas.unset,
        skillTypeDesc: typing.Union[MetaOapg.properties.skillTypeDesc, str, schemas.Unset] = schemas.unset,
        skillTypeId: typing.Union[MetaOapg.properties.skillTypeId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        skillTypeName: typing.Union[MetaOapg.properties.skillTypeName, str, schemas.Unset] = schemas.unset,
        skillViewModelList: typing.Union[MetaOapg.properties.skillViewModelList, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SkillTypeModel':
        return super().__new__(
            cls,
            *args,
            cid=cid,
            createUserId=createUserId,
            createts=createts,
            skillTypeDesc=skillTypeDesc,
            skillTypeId=skillTypeId,
            skillTypeName=skillTypeName,
            skillViewModelList=skillViewModelList,
            _configuration=_configuration,
            **kwargs,
        )

from clay_hr_python_sdk.model.skill_view_model import SkillViewModel
