# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from clay_hr_python_sdk import schemas  # noqa: F401


class UserViewModel(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            adpAssociateOID = schemas.StrSchema
            allocation = schemas.Float64Schema
            careerPathwayId = schemas.Int32Schema
            cellPhone = schemas.StrSchema
            cid = schemas.Int32Schema
            countryId = schemas.Int32Schema
            createuserid = schemas.Int32Schema
            department = schemas.StrSchema
            departmentId = schemas.Int32Schema
            email = schemas.StrSchema
            empId = schemas.StrSchema
            firstName = schemas.StrSchema
            gender = schemas.StrSchema
            guid = schemas.StrSchema
            hasAccess = schemas.Int32Schema
            im = schemas.StrSchema
            imageName = schemas.StrSchema
            jobTitle = schemas.StrSchema
            lastName = schemas.StrSchema
            location = schemas.StrSchema
            locationId = schemas.Int32Schema
            name = schemas.StrSchema
            notes = schemas.StrSchema
            phone = schemas.StrSchema
            profileId = schemas.Int32Schema
            profileName = schemas.StrSchema
            shortName = schemas.StrSchema
            star = schemas.Int32Schema
            status = schemas.StrSchema
            thumbnail = schemas.StrSchema
            timezone = schemas.StrSchema
            userDateFormat = schemas.StrSchema
            userDateOfBirth = schemas.DateSchema
            userEndDate = schemas.DateSchema
            userId = schemas.Int32Schema
            userStartDate = schemas.DateSchema
            userType = schemas.StrSchema
            workerType = schemas.StrSchema
            id = schemas.Int32Schema
            __annotations__ = {
                "adpAssociateOID": adpAssociateOID,
                "allocation": allocation,
                "careerPathwayId": careerPathwayId,
                "cellPhone": cellPhone,
                "cid": cid,
                "countryId": countryId,
                "createuserid": createuserid,
                "department": department,
                "departmentId": departmentId,
                "email": email,
                "empId": empId,
                "firstName": firstName,
                "gender": gender,
                "guid": guid,
                "hasAccess": hasAccess,
                "im": im,
                "imageName": imageName,
                "jobTitle": jobTitle,
                "lastName": lastName,
                "location": location,
                "locationId": locationId,
                "name": name,
                "notes": notes,
                "phone": phone,
                "profileId": profileId,
                "profileName": profileName,
                "shortName": shortName,
                "star": star,
                "status": status,
                "thumbnail": thumbnail,
                "timezone": timezone,
                "userDateFormat": userDateFormat,
                "userDateOfBirth": userDateOfBirth,
                "userEndDate": userEndDate,
                "userId": userId,
                "userStartDate": userStartDate,
                "userType": userType,
                "workerType": workerType,
                "id": id,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["adpAssociateOID"]) -> MetaOapg.properties.adpAssociateOID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allocation"]) -> MetaOapg.properties.allocation: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["careerPathwayId"]) -> MetaOapg.properties.careerPathwayId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cellPhone"]) -> MetaOapg.properties.cellPhone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cid"]) -> MetaOapg.properties.cid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["countryId"]) -> MetaOapg.properties.countryId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createuserid"]) -> MetaOapg.properties.createuserid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["department"]) -> MetaOapg.properties.department: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["departmentId"]) -> MetaOapg.properties.departmentId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["empId"]) -> MetaOapg.properties.empId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["firstName"]) -> MetaOapg.properties.firstName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gender"]) -> MetaOapg.properties.gender: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["guid"]) -> MetaOapg.properties.guid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hasAccess"]) -> MetaOapg.properties.hasAccess: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["im"]) -> MetaOapg.properties.im: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["imageName"]) -> MetaOapg.properties.imageName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobTitle"]) -> MetaOapg.properties.jobTitle: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lastName"]) -> MetaOapg.properties.lastName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["location"]) -> MetaOapg.properties.location: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locationId"]) -> MetaOapg.properties.locationId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["notes"]) -> MetaOapg.properties.notes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phone"]) -> MetaOapg.properties.phone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["profileId"]) -> MetaOapg.properties.profileId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["profileName"]) -> MetaOapg.properties.profileName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shortName"]) -> MetaOapg.properties.shortName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["star"]) -> MetaOapg.properties.star: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["thumbnail"]) -> MetaOapg.properties.thumbnail: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timezone"]) -> MetaOapg.properties.timezone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userDateFormat"]) -> MetaOapg.properties.userDateFormat: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userDateOfBirth"]) -> MetaOapg.properties.userDateOfBirth: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userEndDate"]) -> MetaOapg.properties.userEndDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userId"]) -> MetaOapg.properties.userId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userStartDate"]) -> MetaOapg.properties.userStartDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userType"]) -> MetaOapg.properties.userType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["workerType"]) -> MetaOapg.properties.workerType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["adpAssociateOID", "allocation", "careerPathwayId", "cellPhone", "cid", "countryId", "createuserid", "department", "departmentId", "email", "empId", "firstName", "gender", "guid", "hasAccess", "im", "imageName", "jobTitle", "lastName", "location", "locationId", "name", "notes", "phone", "profileId", "profileName", "shortName", "star", "status", "thumbnail", "timezone", "userDateFormat", "userDateOfBirth", "userEndDate", "userId", "userStartDate", "userType", "workerType", "id", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["adpAssociateOID"]) -> typing.Union[MetaOapg.properties.adpAssociateOID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allocation"]) -> typing.Union[MetaOapg.properties.allocation, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["careerPathwayId"]) -> typing.Union[MetaOapg.properties.careerPathwayId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cellPhone"]) -> typing.Union[MetaOapg.properties.cellPhone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cid"]) -> typing.Union[MetaOapg.properties.cid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["countryId"]) -> typing.Union[MetaOapg.properties.countryId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createuserid"]) -> typing.Union[MetaOapg.properties.createuserid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["department"]) -> typing.Union[MetaOapg.properties.department, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["departmentId"]) -> typing.Union[MetaOapg.properties.departmentId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> typing.Union[MetaOapg.properties.email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["empId"]) -> typing.Union[MetaOapg.properties.empId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["firstName"]) -> typing.Union[MetaOapg.properties.firstName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gender"]) -> typing.Union[MetaOapg.properties.gender, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["guid"]) -> typing.Union[MetaOapg.properties.guid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hasAccess"]) -> typing.Union[MetaOapg.properties.hasAccess, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["im"]) -> typing.Union[MetaOapg.properties.im, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["imageName"]) -> typing.Union[MetaOapg.properties.imageName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobTitle"]) -> typing.Union[MetaOapg.properties.jobTitle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lastName"]) -> typing.Union[MetaOapg.properties.lastName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["location"]) -> typing.Union[MetaOapg.properties.location, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locationId"]) -> typing.Union[MetaOapg.properties.locationId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["notes"]) -> typing.Union[MetaOapg.properties.notes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phone"]) -> typing.Union[MetaOapg.properties.phone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["profileId"]) -> typing.Union[MetaOapg.properties.profileId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["profileName"]) -> typing.Union[MetaOapg.properties.profileName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shortName"]) -> typing.Union[MetaOapg.properties.shortName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["star"]) -> typing.Union[MetaOapg.properties.star, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["thumbnail"]) -> typing.Union[MetaOapg.properties.thumbnail, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timezone"]) -> typing.Union[MetaOapg.properties.timezone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userDateFormat"]) -> typing.Union[MetaOapg.properties.userDateFormat, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userDateOfBirth"]) -> typing.Union[MetaOapg.properties.userDateOfBirth, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userEndDate"]) -> typing.Union[MetaOapg.properties.userEndDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userId"]) -> typing.Union[MetaOapg.properties.userId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userStartDate"]) -> typing.Union[MetaOapg.properties.userStartDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userType"]) -> typing.Union[MetaOapg.properties.userType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["workerType"]) -> typing.Union[MetaOapg.properties.workerType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["adpAssociateOID", "allocation", "careerPathwayId", "cellPhone", "cid", "countryId", "createuserid", "department", "departmentId", "email", "empId", "firstName", "gender", "guid", "hasAccess", "im", "imageName", "jobTitle", "lastName", "location", "locationId", "name", "notes", "phone", "profileId", "profileName", "shortName", "star", "status", "thumbnail", "timezone", "userDateFormat", "userDateOfBirth", "userEndDate", "userId", "userStartDate", "userType", "workerType", "id", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        adpAssociateOID: typing.Union[MetaOapg.properties.adpAssociateOID, str, schemas.Unset] = schemas.unset,
        allocation: typing.Union[MetaOapg.properties.allocation, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        careerPathwayId: typing.Union[MetaOapg.properties.careerPathwayId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        cellPhone: typing.Union[MetaOapg.properties.cellPhone, str, schemas.Unset] = schemas.unset,
        cid: typing.Union[MetaOapg.properties.cid, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        countryId: typing.Union[MetaOapg.properties.countryId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        createuserid: typing.Union[MetaOapg.properties.createuserid, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        department: typing.Union[MetaOapg.properties.department, str, schemas.Unset] = schemas.unset,
        departmentId: typing.Union[MetaOapg.properties.departmentId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        email: typing.Union[MetaOapg.properties.email, str, schemas.Unset] = schemas.unset,
        empId: typing.Union[MetaOapg.properties.empId, str, schemas.Unset] = schemas.unset,
        firstName: typing.Union[MetaOapg.properties.firstName, str, schemas.Unset] = schemas.unset,
        gender: typing.Union[MetaOapg.properties.gender, str, schemas.Unset] = schemas.unset,
        guid: typing.Union[MetaOapg.properties.guid, str, schemas.Unset] = schemas.unset,
        hasAccess: typing.Union[MetaOapg.properties.hasAccess, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        im: typing.Union[MetaOapg.properties.im, str, schemas.Unset] = schemas.unset,
        imageName: typing.Union[MetaOapg.properties.imageName, str, schemas.Unset] = schemas.unset,
        jobTitle: typing.Union[MetaOapg.properties.jobTitle, str, schemas.Unset] = schemas.unset,
        lastName: typing.Union[MetaOapg.properties.lastName, str, schemas.Unset] = schemas.unset,
        location: typing.Union[MetaOapg.properties.location, str, schemas.Unset] = schemas.unset,
        locationId: typing.Union[MetaOapg.properties.locationId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        notes: typing.Union[MetaOapg.properties.notes, str, schemas.Unset] = schemas.unset,
        phone: typing.Union[MetaOapg.properties.phone, str, schemas.Unset] = schemas.unset,
        profileId: typing.Union[MetaOapg.properties.profileId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        profileName: typing.Union[MetaOapg.properties.profileName, str, schemas.Unset] = schemas.unset,
        shortName: typing.Union[MetaOapg.properties.shortName, str, schemas.Unset] = schemas.unset,
        star: typing.Union[MetaOapg.properties.star, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        thumbnail: typing.Union[MetaOapg.properties.thumbnail, str, schemas.Unset] = schemas.unset,
        timezone: typing.Union[MetaOapg.properties.timezone, str, schemas.Unset] = schemas.unset,
        userDateFormat: typing.Union[MetaOapg.properties.userDateFormat, str, schemas.Unset] = schemas.unset,
        userDateOfBirth: typing.Union[MetaOapg.properties.userDateOfBirth, str, date, schemas.Unset] = schemas.unset,
        userEndDate: typing.Union[MetaOapg.properties.userEndDate, str, date, schemas.Unset] = schemas.unset,
        userId: typing.Union[MetaOapg.properties.userId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        userStartDate: typing.Union[MetaOapg.properties.userStartDate, str, date, schemas.Unset] = schemas.unset,
        userType: typing.Union[MetaOapg.properties.userType, str, schemas.Unset] = schemas.unset,
        workerType: typing.Union[MetaOapg.properties.workerType, str, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UserViewModel':
        return super().__new__(
            cls,
            *args,
            adpAssociateOID=adpAssociateOID,
            allocation=allocation,
            careerPathwayId=careerPathwayId,
            cellPhone=cellPhone,
            cid=cid,
            countryId=countryId,
            createuserid=createuserid,
            department=department,
            departmentId=departmentId,
            email=email,
            empId=empId,
            firstName=firstName,
            gender=gender,
            guid=guid,
            hasAccess=hasAccess,
            im=im,
            imageName=imageName,
            jobTitle=jobTitle,
            lastName=lastName,
            location=location,
            locationId=locationId,
            name=name,
            notes=notes,
            phone=phone,
            profileId=profileId,
            profileName=profileName,
            shortName=shortName,
            star=star,
            status=status,
            thumbnail=thumbnail,
            timezone=timezone,
            userDateFormat=userDateFormat,
            userDateOfBirth=userDateOfBirth,
            userEndDate=userEndDate,
            userId=userId,
            userStartDate=userStartDate,
            userType=userType,
            workerType=workerType,
            id=id,
            _configuration=_configuration,
            **kwargs,
        )
