# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCustomFieldValueModel(TypedDict):
    pass

class OptionalCustomFieldValueModel(TypedDict, total=False):
    cid: int

    createUserId: int

    customFieldId: int

    customFieldObjectId: int

    customFieldValue: str

    customFieldValueId: int

    customfieldName: str

class CustomFieldValueModel(RequiredCustomFieldValueModel, OptionalCustomFieldValueModel):
    pass
