# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.custom_table_column_value_model import CustomTableColumnValueModel
from clay_hr_python_sdk.type.timestamp import Timestamp
from clay_hr_python_sdk.type.user_view_model import UserViewModel

class RequiredCustomTableValueModel(TypedDict):
    pass

class OptionalCustomTableValueModel(TypedDict, total=False):
    candidateId: int

    cid: int

    createUserId: int

    createts: Timestamp

    ctColumnValueList: typing.List[CustomTableColumnValueModel]

    ctValueId: int

    customTableId: int

    userId: int

    userModel: UserViewModel

class CustomTableValueModel(RequiredCustomTableValueModel, OptionalCustomTableValueModel):
    pass
