# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCustomListEntryModel(TypedDict):
    pass

class OptionalCustomListEntryModel(TypedDict, total=False):
    cid: int

    entryCode: str

    entryId: int

    entryValue: str

    listId: int

class CustomListEntryModel(RequiredCustomListEntryModel, OptionalCustomListEntryModel):
    pass
