# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.custom_field_model import CustomFieldModel
from clay_hr_python_sdk.type.timestamp import Timestamp

class RequiredEmploymentModel(TypedDict):
    pass

class OptionalEmploymentModel(TypedDict, total=False):
    SOCCode: str

    cid: int

    city: str

    countryId: int

    createts: Timestamp

    custAppId: int

    customFieldModelList: typing.List[CustomFieldModel]

    department: str

    duties: str

    empId: int

    employerName: str

    employerTypeBus: str

    employmentType: str

    endDate: date

    naicscode: str

    position: str

    recruitid: int

    soccode: str

    startDate: date

    state: str

    userId: int

class EmploymentModel(RequiredEmploymentModel, OptionalEmploymentModel):
    pass
