# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.goals_get_goal_response_goal_collaboration_model_item_user_model import GoalsGetGoalResponseGoalCollaborationModelItemUserModel

class RequiredGoalsGetGoalResponseGoalCollaborationModelItem(TypedDict):
    pass

class OptionalGoalsGetGoalResponseGoalCollaborationModelItem(TypedDict, total=False):
    collabid: str

    goalid: str

    userid: str

    extuserid: str

    cid: str

    userModel: GoalsGetGoalResponseGoalCollaborationModelItemUserModel

    extuserModel: str

class GoalsGetGoalResponseGoalCollaborationModelItem(RequiredGoalsGetGoalResponseGoalCollaborationModelItem, OptionalGoalsGetGoalResponseGoalCollaborationModelItem):
    pass
