# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.goals_get_goal_response_goal_type_model_assessment_model_range_model_list import GoalsGetGoalResponseGoalTypeModelAssessmentModelRangeModelList

class RequiredGoalsGetGoalResponseGoalTypeModelAssessmentModel(TypedDict):
    pass

class OptionalGoalsGetGoalResponseGoalTypeModelAssessmentModel(TypedDict, total=False):
    scoretemplateid: str

    cid: str

    scoreMin: str

    scoreMax: str

    scoreMaxValidation: str

    scoringInstructions: str

    scoreName: str

    allowFractional: str

    rangeModelList: GoalsGetGoalResponseGoalTypeModelAssessmentModelRangeModelList

    visualizationType: str

    status: str

class GoalsGetGoalResponseGoalTypeModelAssessmentModel(RequiredGoalsGetGoalResponseGoalTypeModelAssessmentModel, OptionalGoalsGetGoalResponseGoalTypeModelAssessmentModel):
    pass
