# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.address_model import AddressModel

class RequiredLocationModel(TypedDict):
    pass

class OptionalLocationModel(TypedDict, total=False):
    address: str

    addressModelList: typing.List[AddressModel]

    cid: int

    createuserid: int

    lattitude: str

    locationCode: str

    locationDescription: str

    locationId: int

    locationLabel: str

    locationName: str

    locationType: str

    locationUID: str

    longitude: str

    parentLocationId: int

    status: str

    workingDays: str

class LocationModel(RequiredLocationModel, OptionalLocationModel):
    pass
