# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListItem(TypedDict):
    pass

class OptionalPeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListItem(TypedDict, total=False):
    name: str

    lastName: str

    relationToUser: str

    contactType: str

    gender: str

    taxNumber: str

    dateOfBirth: str

    status: str

    extAppUID: str

class PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListItem(RequiredPeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListItem, OptionalPeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListItem):
    pass
