# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPeopleAndPermissionsUploadUserProfilePictureResponse(TypedDict):
    pass

class OptionalPeopleAndPermissionsUploadUserProfilePictureResponse(TypedDict, total=False):
    imageName: str

    data: str

    message: str

class PeopleAndPermissionsUploadUserProfilePictureResponse(RequiredPeopleAndPermissionsUploadUserProfilePictureResponse, OptionalPeopleAndPermissionsUploadUserProfilePictureResponse):
    pass
