# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.candidate_applications_model import CandidateApplicationsModel
from clay_hr_python_sdk.type.location_model import LocationModel
from clay_hr_python_sdk.type.position_approval_level_model import PositionApprovalLevelModel
if TYPE_CHECKING:
    from clay_hr_python_sdk.type.project_model import ProjectModel
from clay_hr_python_sdk.type.user_position_approval_model import UserPositionApprovalModel
from clay_hr_python_sdk.type.user_profile_model import UserProfileModel
from clay_hr_python_sdk.type.user_view_model import UserViewModel

class RequiredPositionModel(TypedDict):
    pass

class OptionalPositionModel(TypedDict, total=False):
    description: str

    accessLevel: str

    applicationDueDate: date

    applicationFormId: int

    approvalFlowId: int

    approvalStatus: str

    assessmentFormId: int

    assessmentTemplateId: int

    candidatePositionModelList: typing.List[CandidateApplicationsModel]

    cid: int

    count: int

    createDate: date

    createUserId: int

    customLocation: str

    dateClose: date

    departmentId: int

    funnelId: int

    hiringManagerId: int

    htmlTemplate: str

    isRecommended: bool

    lastUpdatets: date

    lastupdateuserid: int

    locationModel: LocationModel

    locationid: int

    name: str

    positionApprovalLevelList: typing.List[PositionApprovalLevelModel]

    positionUID: str

    positionid: int

    profileModel: UserProfileModel

    profileid: int

    projectModel: 'ProjectModel'

    projectid: int

    recommended: bool

    recruiterId: int

    recruiterModel: UserViewModel

    requestApprovalId: int

    requirements: str

    responsibilities: str

    seoUrl: str

    status: str

    totalcandidate: int

    userName: str

    userViewModel: UserViewModel

    userapprovalList: typing.List[UserPositionApprovalModel]

    id: int

class PositionModel(RequiredPositionModel, OptionalPositionModel):
    pass
