# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.skills_create_new_skill_request_assessment_model_range_model_list import SkillsCreateNewSkillRequestAssessmentModelRangeModelList

class RequiredSkillsCreateNewSkillRequestAssessmentModel(TypedDict):
    # The ID of the assessment scale.
    scoretemplateid: int

class OptionalSkillsCreateNewSkillRequestAssessmentModel(TypedDict, total=False):
    rangeModelList: SkillsCreateNewSkillRequestAssessmentModelRangeModelList

    # Maximum score of the assessment.
    scoreMax: typing.Union[int, float]

    # Minimum score of the assessment.
    scoreMin: typing.Union[int, float]

    # Name of the score.
    scoreName: str

    # Status of the assessment.   A -Active, ARCHV -Archive
    status: str

class SkillsCreateNewSkillRequestAssessmentModel(RequiredSkillsCreateNewSkillRequestAssessmentModel, OptionalSkillsCreateNewSkillRequestAssessmentModel):
    pass
