# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTimecardsGetDetailsByTimecardId404Response(TypedDict):
    pass

class OptionalTimecardsGetDetailsByTimecardId404Response(TypedDict, total=False):
    message: str

class TimecardsGetDetailsByTimecardId404Response(RequiredTimecardsGetDetailsByTimecardId404Response, OptionalTimecardsGetDetailsByTimecardId404Response):
    pass
