# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.timesheets_get_approval_list_response_data import TimesheetsGetApprovalListResponseData

class RequiredTimesheetsGetApprovalListResponse(TypedDict):
    pass

class OptionalTimesheetsGetApprovalListResponse(TypedDict, total=False):
    data: TimesheetsGetApprovalListResponseData

    message: str

class TimesheetsGetApprovalListResponse(RequiredTimesheetsGetApprovalListResponse, OptionalTimesheetsGetApprovalListResponse):
    pass
