# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.address_model import AddressModel
from clay_hr_python_sdk.type.award_model import AwardModel
from clay_hr_python_sdk.type.bank_account_model import BankAccountModel
from clay_hr_python_sdk.type.certification_model import CertificationModel
from clay_hr_python_sdk.type.custom_field_value_model import CustomFieldValueModel
from clay_hr_python_sdk.type.custom_table_model import CustomTableModel
from clay_hr_python_sdk.type.department_model import DepartmentModel
from clay_hr_python_sdk.type.education_model import EducationModel
from clay_hr_python_sdk.type.employment_model import EmploymentModel
from clay_hr_python_sdk.type.financial_model import FinancialModel
from clay_hr_python_sdk.type.hr_calendar_model import HRCalendarModel
from clay_hr_python_sdk.type.location_model import LocationModel
if TYPE_CHECKING:
    from clay_hr_python_sdk.type.project_model import ProjectModel
from clay_hr_python_sdk.type.skill_user_model import SkillUserModel
from clay_hr_python_sdk.type.timestamp import Timestamp
from clay_hr_python_sdk.type.user_model_reports_to_list_map import UserModelReportsToListMap
from clay_hr_python_sdk.type.user_profile_model import UserProfileModel
from clay_hr_python_sdk.type.user_thin_model import UserThinModel
from clay_hr_python_sdk.type.user_training_model import UserTrainingModel
from clay_hr_python_sdk.type.worker_type_model import WorkerTypeModel

class RequiredUserModel(TypedDict):
    userId: int

class OptionalUserModel(TypedDict, total=False):
    addressModelList: typing.List[AddressModel]

    adpAssociateOID: str

    allocation: typing.Union[int, float]

    appleUserIdentifier: str

    assignments: str

    awardModelList: typing.List[AwardModel]

    bankAccountModel: BankAccountModel

    calWeekPref: str

    calendarId: int

    calendarModel: HRCalendarModel

    candidateId: int

    careerPathwayId: int

    cellPhone: str

    cid: int

    countryId: int

    createts: Timestamp

    customFieldValueModelList: typing.List[CustomFieldValueModel]

    customTableModelList: 'typing.List[CustomTableModel]'

    departmentModel: DepartmentModel

    departmentName: str

    displayFullName: str

    educationModelList: typing.List[EducationModel]

    email: str

    empId: str

    employmentModelList: typing.List[EmploymentModel]

    familySuffix: str

    financialModelList: typing.List[FinancialModel]

    firstName: str

    gender: str

    guid: str

    hasAccess: bool

    hrPortal: str

    im: str

    imageName: str

    isView: bool

    jobGrade: str

    languagePreference: str

    lastName: str

    lastUpdateUsername: str

    lastupdatets: date

    lastupdateuserid: int

    licenseModelList: typing.List[CertificationModel]

    locationModel: LocationModel

    mfaPreference: bool

    mfaSecretKey: str

    middleName: str

    namePronunciation: str

    notifications: bool

    paId: int

    phone: str

    position: str

    prefixSalutation: str

    profileId: int

    profileName: str

    projectModel: 'ProjectModel'

    projectModelList: 'typing.List[ProjectModel]'

    ptoannual: typing.Union[int, float]

    ptobalance: typing.Union[int, float]

    qboPref: int

    relativeDate: str

    reportsToListMap: UserModelReportsToListMap

    secondLastName: str

    shortName: str

    skillUserModelList: 'typing.List[SkillUserModel]'

    star: int

    status: str

    stripeId: str

    supervisorModelList: typing.List[UserThinModel]

    thumbnail: str

    timecardPeriodPref: str

    timezone: str

    tosVersion: str

    userCountry: str

    userDateFormat: str

    userDateOfBirth: date

    userDisplayName: str

    userEndDate: date

    userNameFormat: str

    userProfileModel: UserProfileModel

    userStartDate: date

    userTrainingModelList: 'typing.List[UserTrainingModel]'

    userType: str

    view: bool

    workerType: str

    workerTypeModel: WorkerTypeModel

    workingDays: str

    userName: str

class UserModel(RequiredUserModel, OptionalUserModel):
    pass
