# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.user_view_model import UserViewModel

class RequiredUserPositionApprovalModel(TypedDict):
    pass

class OptionalUserPositionApprovalModel(TypedDict, total=False):
    cid: int

    positionId: int

    position_approval_id: int

    status: str

    userId: int

    userViewModel: UserViewModel

class UserPositionApprovalModel(RequiredUserPositionApprovalModel, OptionalUserPositionApprovalModel):
    pass
