# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUserViewModel(TypedDict):
    pass

class OptionalUserViewModel(TypedDict, total=False):
    adpAssociateOID: str

    allocation: typing.Union[int, float]

    careerPathwayId: int

    cellPhone: str

    cid: int

    countryId: int

    createuserid: int

    department: str

    departmentId: int

    email: str

    empId: str

    firstName: str

    gender: str

    guid: str

    hasAccess: int

    im: str

    imageName: str

    jobTitle: str

    lastName: str

    location: str

    locationId: int

    name: str

    notes: str

    phone: str

    profileId: int

    profileName: str

    shortName: str

    star: int

    status: str

    thumbnail: str

    timezone: str

    userDateFormat: str

    userDateOfBirth: date

    userEndDate: date

    userId: int

    userStartDate: date

    userType: str

    workerType: str

    id: int

class UserViewModel(RequiredUserViewModel, OptionalUserViewModel):
    pass
