# coding: utf-8

"""
    Expense Reports

    API Documentation

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clay_hr_python_sdk.type.workflow_parameter_model import WorkflowParameterModel

class RequiredWorkflowParameterAssignmentModel(TypedDict):
    pass

class OptionalWorkflowParameterAssignmentModel(TypedDict, total=False):
    cid: int

    paramName: str

    paramValue: str

    parameterModel: WorkflowParameterModel

    userWorkflowid: int

    waParamId: int

    workflowArgId: int

class WorkflowParameterAssignmentModel(RequiredWorkflowParameterAssignmentModel, OptionalWorkflowParameterAssignmentModel):
    pass
